//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int Song_Id { get; set; }
        public string Name { get; set; }
        public System.TimeSpan Length { get; set; }
        public Nullable<decimal> Bitrate { get; set; }
        public Nullable<decimal> Size { get; set; }
        public string Genere { get; set; }
        public int Artist { get; set; }
    
        public virtual Artist Artist1 { get; set; }
    }
}
